include_directories(
    ${CMAKE_CURRENT_LIST_DIR}/include)

set(ENGINE_SOURCE
    ${CMAKE_CURRENT_LIST_DIR}/src/main.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Engine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Editor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/BCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Island.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/EditorStates.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/triangulate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/ColShape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Collision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/GameWorld.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Game.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Components.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/entities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Protagonist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/systems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Camera.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/FrameTimer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/EntityEditor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/MoveSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/imgui_impl_glfw_gl3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/WRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/WShader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/WTexture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/WInput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/SceneIO.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/NavMesh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/SimpleFlyer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/CollisionComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Pathfinding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/SkillComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/CPruneSweep.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/TagComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/Actor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/HurtBoxComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/StatusEffectComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/AIComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/ai_state_transitions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/ai_state_funcs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/ai_input_funcs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/PatrolComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/PosComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/steering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/EditorDraw.cpp
    )
