include_directories(
    ${CMAKE_CURRENT_LIST_DIR})

set(ENGINE_SOURCE
    ${CMAKE_CURRENT_LIST_DIR}/main.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Engine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Editor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Island.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EditorStates.cpp
    ${CMAKE_CURRENT_LIST_DIR}/triangulate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ColShape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Collision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GameWorld.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Game.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components.cpp
    ${CMAKE_CURRENT_LIST_DIR}/entities.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Protagonist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/systems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Camera.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FrameTimer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EntityEditor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MoveSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/imgui_impl_glfw_gl3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WShader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WTexture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WInput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SceneIO.cpp
    ${CMAKE_CURRENT_LIST_DIR}/NavMesh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SimpleFlyer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CollisionComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Pathfinding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SkillComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CPruneSweep.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TagComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Actor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HurtBoxComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/StatusEffectComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AIComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ai_state_transitions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ai_state_funcs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ai_input_funcs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PatrolComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PosComponent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/steering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EditorDraw.cpp
    )
